name: Publish SDK

on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Setup NodeJS"
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Ensure NPM access
      run: |
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Setup Git
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
    - run: yarn install --frozen-lockfile

    # The NX target "ci-version" has postTargets=[build, ci-publish]
    - name: "Version, Build, Publish"
      shell: bash
      run: yarn nx affected --target ci-version --base= origin/main~1 --head= HEAD --parallel=1 --exclude=demoreact

    - name: "Push GIT Tags"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        git push origin main --follow-tags